// AUTO-GENERATED from arts/猪八戒.png by tmp_art/build_party.py - do not edit by hand.
// 月色（moonlit）像素猪八戒：front-view run + idle 帧。'.' = 透明。
// feetRow = 角色脚底所在行（用于让脚踩在地面 y 上）。

export const BAJIE = {
  w: 28,
  h: 26,
  feetRow: 25,
  palette: {
    '.': null,
    'a': '#b07231',
    'b': '#95652f',
    'c': '#905729',
    'd': '#856635',
    'e': '#3a3b3f',
    'f': '#333337',
    'g': '#653b1f',
    'h': '#6c4524',
    'i': '#7f5325',
    'j': '#332c2b',
    'k': '#564e3f',
    'l': '#704e29',
    'm': '#5a3a25',
    'n': '#584533',
    'o': '#825a24',
    'p': '#645b45',
    'q': '#2c2120',
    'r': '#b7915d',
    's': '#b48046',
    't': '#4d392c',
    'u': '#ca9f75',
    'v': '#c5895c',
    'w': '#dd9f65',
    'x': '#c6b991',
    'y': '#ead1a3',
    'z': '#a38462',
    'A': '#df8b46',
    'B': '#976f3a',
    'C': '#492f21',
    'D': '#82461e',
    'E': '#eab97d',
    'F': '#695432',
    'G': '#4e3627',
    'H': '#fdfbe6',
    'I': '#f4dc96',
    'J': '#f2c98d',
    'K': '#6e5029',
    'L': '#d6deec',
    'M': '#282030',
    'N': '#96a8c8',
    'O': '#3c3242',
  },
  run: [
    [
      '............................',
      '............................',
      '..................abb.......',
      '.................bcbbbbbbd..',
      '............eef....gghiicbb.',
      '..........jeekke.....lclghm.',
      '.........jfenaadf....oai....',
      '........pqharsssotu..hi.....',
      '......vwudsxyyyyuzwv.ol.....',
      '......sAauyxzyyuxsAA.g......',
      '.......wAsyuzuwBuvA..t......',
      '........lbyyxssvyu...t......',
      '.......CDauEwwuvh..tt.......',
      '......jeeDDDichDtf.C........',
      '......eefBsDghDspfdF........',
      '.....fkffaEzuyzudnaE........',
      '.....ddhtbuyxuyuimmB........',
      '....mhuphCClaaijCmCq........',
      '....qmwkbslgghgiihGG........',
      '..yy.qqnavdmmCgdahG.........',
      '.yHHI.lbCzpjchmpnjm.yHy.....',
      '.JIII..GlhjhiGDCkzq.IHHJ....',
      '..........KK..KK............',
      '..........AK..AK............',
      '........L.MM.LMMN...........',
      '.........OMM..MMO...........',
    ],
    [
      '...................abb......',
      '..................bcbbbbbbd.',
      '.............eef....gghiicbb',
      '...........jeekke.....lclghm',
      '..........jfenaadf....oai...',
      '.........pqharsssotu..hi....',
      '.......vwudsxyyyyuzwv.ol....',
      '.......sAauyxzyyuxsAA.g.....',
      '........wAsyuzuwBuvA..t.....',
      '.........lbyyxssvyu...t.....',
      '........CDauEwwuvh..tt......',
      '.......jeeDDDichDtf.C.......',
      '.......eefBsDghDspfdF.......',
      '......fkffaEzuyzudnaE.......',
      '......ddhtbuyxuyuimmB.......',
      '.....mhuphCClaaijCmCq.......',
      '.....qmwkbslgghgiihGG.......',
      '...yy.qqnavdmmCgdahG........',
      '..yHHI.lbCzpjchmpnjm.yHy....',
      '..JIII..GlhjhiGDCkzq.IHHJ...',
      '...........AK...............',
      '...........MM.KK............',
      '..........OMM.KK............',
      '..............AK............',
      '..............MMN...........',
      '..............MMO...........',
    ],
    [
      '...................abb......',
      '..................bcbbbbbbd.',
      '.............eef....gghiicbb',
      '...........jeekke.....lclghm',
      '..........jfenaadf....oai...',
      '.........pqharsssotu..hi....',
      '.......vwudsxyyyyuzwv.ol....',
      '.......sAauyxzyyuxsAA.g.....',
      '........wAsyuzuwBuvA..t.....',
      '.........lbyyxssvyu...t.....',
      '........CDauEwwuvh..tt......',
      '.......jeeDDDichDtf.C.......',
      '.......eefBsDghDspfdF.......',
      '......fkffaEzuyzudnaE.......',
      '......ddhtbuyxuyuimmB.......',
      '.....mhuphCClaaijCmCq.......',
      '.....qmwkbslgghgiihGG.......',
      '...yy.qqnavdmmCgdahG........',
      '..yHHI.lbCzpjchmpnjm.yHy....',
      '..JIII..GlhjhiGDCkzq.IHHJ...',
      '...........AK...............',
      '...........MM.KK............',
      '..........OMM.KK............',
      '..............AK............',
      '.............LMMN...........',
      '..............MMO...........',
    ],
    [
      '............................',
      '............................',
      '..................abb.......',
      '.................bcbbbbbbd..',
      '............eef....gghiicbb.',
      '..........jeekke.....lclghm.',
      '.........jfenaadf....oai....',
      '........pqharsssotu..hi.....',
      '......vwudsxyyyyuzwv.ol.....',
      '......sAauyxzyyuxsAA.g......',
      '.......wAsyuzuwBuvA..t......',
      '........lbyyxssvyu...t......',
      '.......CDauEwwuvh..tt.......',
      '......jeeDDDichDtf.C........',
      '......eefBsDghDspfdF........',
      '.....fkffaEzuyzudnaE........',
      '.....ddhtbuyxuyuimmB........',
      '....mhuphCClaaijCmCq........',
      '....qmwkbslgghgiihGG........',
      '..yy.qqnavdmmCgdahG.........',
      '.yHHI.lbCzpjchmpnjm.yHy.....',
      '.JIII..GlhjhiGDCkzq.IHHJ....',
      '..........KK..KK............',
      '..........AK..AK............',
      '..........MM..MMN...........',
      '.........OMM..MMO...........',
    ],
    [
      '.................abb........',
      '................bcbbbbbbd...',
      '...........eef....gghiicbb..',
      '.........jeekke.....lclghm..',
      '........jfenaadf....oai.....',
      '.......pqharsssotu..hi......',
      '.....vwudsxyyyyuzwv.ol......',
      '.....sAauyxzyyuxsAA.g.......',
      '......wAsyuzuwBuvA..t.......',
      '.......lbyyxssvyu...t.......',
      '......CDauEwwuvh..tt........',
      '.....jeeDDDichDtf.C.........',
      '.....eefBsDghDspfdF.........',
      '....fkffaEzuyzudnaE.........',
      '....ddhtbuyxuyuimmB.........',
      '...mhuphCClaaijCmCq.........',
      '...qmwkbslgghgiihGG.........',
      '.yy.qqnavdmmCgdahG..........',
      'yHHI.lbCzpjchmpnjm.yHy......',
      'JIII..GlhjhiGDCkzq.IHHJ.....',
      '.............AK.............',
      '..........KK.MM.............',
      '..........KK.MMO............',
      '..........AK................',
      '........L.MM................',
      '.........OMM................',
    ],
    [
      '.................abb........',
      '................bcbbbbbbd...',
      '...........eef....gghiicbb..',
      '.........jeekke.....lclghm..',
      '........jfenaadf....oai.....',
      '.......pqharsssotu..hi......',
      '.....vwudsxyyyyuzwv.ol......',
      '.....sAauyxzyyuxsAA.g.......',
      '......wAsyuzuwBuvA..t.......',
      '.......lbyyxssvyu...t.......',
      '......CDauEwwuvh..tt........',
      '.....jeeDDDichDtf.C.........',
      '.....eefBsDghDspfdF.........',
      '....fkffaEzuyzudnaE.........',
      '....ddhtbuyxuyuimmB.........',
      '...mhuphCClaaijCmCq.........',
      '...qmwkbslgghgiihGG.........',
      '.yy.qqnavdmmCgdahG..........',
      'yHHI.lbCzpjchmpnjm.yHy......',
      'JIII..GlhjhiGDCkzq.IHHJ.....',
      '.............AK.............',
      '..........KK.MM.............',
      '..........KK.MMO............',
      '..........AK................',
      '..........MM................',
      '.........OMM................',
    ],
  ],
  idle: [
    [
      '............................',
      '............................',
      '..................abb.......',
      '.................bcbbbbbbd..',
      '............eef....gghiicbb.',
      '..........jeekke.....lclghm.',
      '.........jfenaadf....oai....',
      '........pqharsssotu..hi.....',
      '......vwudsxyyyyuzwv.ol.....',
      '......sAauyxzyyuxsAA.g......',
      '.......wAsyuzuwBuvA..t......',
      '........lbyyxssvyu...t......',
      '.......CDauEwwuvh..tt.......',
      '......jeeDDDichDtf.C........',
      '......eefBsDghDspfdF........',
      '.....fkffaEzuyzudnaE........',
      '.....ddhtbuyxuyuimmB........',
      '....mhuphCClaaijCmCq........',
      '....qmwkbslgghgiihGG........',
      '..yy.qqnavdmmCgdahG.........',
      '.yHHI.lbCzpjchmpnjm.yHy.....',
      '.JIII..GlhjhiGDCkzq.IHHJ....',
      '..........KK..KK............',
      '..........AK..AK............',
      '..........MM..MM............',
      '.........OMM..MMO...........',
    ],
    [
      '............................',
      '..................abb.......',
      '.................bcbbbbbbd..',
      '............eef....gghiicbb.',
      '..........jeekke.....lclghm.',
      '.........jfenaadf....oai....',
      '........pqharsssotu..hi.....',
      '......vwudsxyyyyuzwv.ol.....',
      '......sAauyxzyyuxsAA.g......',
      '.......wAsyuzuwBuvA..t......',
      '........lbyyxssvyu...t......',
      '.......CDauEwwuvh..tt.......',
      '......jeeDDDichDtf.C........',
      '......eefBsDghDspfdF........',
      '.....fkffaEzuyzudnaE........',
      '.....ddhtbuyxuyuimmB........',
      '....mhuphCClaaijCmCq........',
      '....qmwkbslgghgiihGG........',
      '..yy.qqnavdmmCgdahG.........',
      '.yHHI.lbCzpjchmpnjm.yHy.....',
      '.JIII..GlhjhiGDCkzq.IHHJ....',
      '..........KK..KK............',
      '..........KK..KK............',
      '..........AK..AK............',
      '..........MM..MM............',
      '.........OMM..MMO...........',
    ],
  ],
};
