// 剧情 NPC 的手绘像素精灵。
// 每个角色有 idle / talk 两组帧；talk 复用角色动画接口中的 run 字段。

const COMMON = {
  '.': null,
  k: '#110d16',
  s: '#f0c28f',
  S: '#d99b6d',
  w: '#f7efe1',
  W: '#d8d0c0',
  g: '#ffce54',
  G: '#b99036',
  r: '#c84a3d',
  R: '#8f2d2b',
  b: '#4f9fbd',
  B: '#2f6078',
  y: '#d8a34b',
  Y: '#8c5d2a',
  n: '#6d482c',
  N: '#3f2a1d',
  e: '#78b86a',
  E: '#3f7a42',
  p: '#e9a9c9',
  P: '#b46a92',
  m: '#8e849b',
  M: '#51455f',
  o: '#f0a05a',
  O: '#a44f33',
};

const baseFeetRow = 21;

function makeNpc(palette, idle, talk = idle) {
  return {
    w: 18,
    h: 22,
    feetRow: baseFeetRow,
    palette: { ...COMMON, ...palette },
    idle,
    run: talk,
  };
}

export const NPC_SPRITES = {
  guanyin: makeNpc(
    { a: '#fff8d6', c: '#86c7b4' },
    [
      [
        '.......ggg........',
        '......g...g.......',
        '.....g.aaa.g......',
        '......kkwkk.......',
        '.....kssssk.......',
        '.....ksgsgk.......',
        '......sSss........',
        '....kwwwwwwk......',
        '...kwwwwwwwwk.....',
        '..kwwwWwwWwwwk....',
        '..kwwwwwwwwwwk....',
        '...kwwcwwcwwk.....',
        '....kwwwwwwk......',
        '....kwwwWwwk......',
        '...kwwwkkwwwk.....',
        '..kwwwwkkwwwwk....',
        '..kwwwk..kwwwk....',
        '...kwwk..kwwk.....',
        '....kWk..kWk......',
        '....kk....kk......',
        '...ppp....ppp.....',
        '..pPPPp..pPPPp....',
      ],
      [
        '.......ggg........',
        '......g...g.......',
        '.....g.aaa.g......',
        '......kkwkk.......',
        '.....kssssk.......',
        '.....ksgsgk.......',
        '......sSss........',
        '....kwwwwwwk......',
        '...kwwwwwwwwk.....',
        '..kwwwWwwWwwwk....',
        '..kwwwwwwwwwwk....',
        '...kwwcwwcwwk.....',
        '....kwwwwwwk......',
        '....kwwwWwwk......',
        '...kwwwkkwwwk.....',
        '..kwwwwkkwwwwk....',
        '..kwwwk..kwwwk....',
        '...kwwk..kwwk.....',
        '....kWk..kWk......',
        '....kk....kk......',
        '..ppp......ppp....',
        '.pPPPp....pPPPp...',
      ],
    ],
    [
      [
        '.......ggg........',
        '......g...g.......',
        '.....g.aaa.g......',
        '......kkwkk.......',
        '.....kssssk.......',
        '.....ksGsgk.......',
        '......sSSs........',
        '....kwwwwwwk......',
        '...kwwwwwwwwk.....',
        '..kwwwWwwWwwwk....',
        '..kwwwwwwwwwwk....',
        '...kwwcwwcwwk.....',
        '....kwwwwwwk......',
        '....kwwwWwwk......',
        '...kwwwkkwwwk.....',
        '..kwwwwkkwwwwk....',
        '..kwwwk..kwwwk....',
        '...kwwk..kwwk.....',
        '....kWk..kWk......',
        '....kk....kk......',
        '...ppp....ppp.....',
        '..pPPPp..pPPPp....',
      ],
      [
        '.......ggg........',
        '......g...g.......',
        '.....g.aaa.g......',
        '......kkwkk.......',
        '.....kssssk.......',
        '.....ksgSGk.......',
        '......sSss........',
        '....kwwwwwwk......',
        '...kwwwwwwwwk.....',
        '..kwwwWwwWwwwk....',
        '..kwwwwwwwwwwk....',
        '...kwwcwwcwwk.....',
        '....kwwwwwwk......',
        '....kwwwWwwk......',
        '...kwwwkkwwwk.....',
        '..kwwwwkkwwwwk....',
        '..kwwwk..kwwwk....',
        '...kwwk..kwwk.....',
        '....kWk..kWk......',
        '....kk....kk......',
        '..ppp......ppp....',
        '.pPPPp....pPPPp...',
      ],
    ]
  ),

  'mountain-god': makeNpc(
    { h: '#4f7f35', H: '#9ccf6e', v: '#2d5930' },
    [
      [
        '......HHH.HH......',
        '.....HhhHHhH......',
        '......kNNNk.......',
        '.....ksSssk.......',
        '.....kskksk.......',
        '.....kNNNNk.......',
        '....knNNNNnk......',
        '...knnEeEennk.....',
        '..knnEeeeEennk....',
        '..knEeEeeEeEnk....',
        '..kNEEvvvEENk.....',
        '...kNEvvvENk......',
        '....kEvvvEk.......',
        '...kEEkvkEEk......',
        '..kEENkkNEEk......',
        '..kENk..kNEk......',
        '...kNk..kNk.......',
        '...kNk..kNk.......',
        '..kNNk..kNNk......',
        '..kkkk..kkkk......',
        '...NN....NN.......',
        '..kNNk..kNNk......',
      ],
      [
        '.....HHH.HHH......',
        '....HhhHHhhH......',
        '......kNNNk.......',
        '.....ksSssk.......',
        '.....kskksk.......',
        '.....kNNNNk.......',
        '....knNNNNnk......',
        '...knnEeEennk.....',
        '..knnEeeeEennk....',
        '..knEeEeeEeEnk....',
        '..kNEEvvvEENk.....',
        '...kNEvvvENk......',
        '....kEvvvEk.......',
        '...kEEkvkEEk......',
        '..kEENkkNEEk......',
        '..kENk..kNEk......',
        '...kNk..kNk.......',
        '...kNk..kNk.......',
        '..kNNk..kNNk......',
        '..kkkk..kkkk......',
        '..NN......NN......',
        '.kNNk....kNNk.....',
      ],
    ],
    [
      [
        '......HHH.HH......',
        '.....HhhHHhH......',
        '......kNNNk.......',
        '.....ksSssk.......',
        '.....kskSsk.......',
        '.....kNNNNk.......',
        '....knNNNNnk......',
        '...knnEeEennk.....',
        '..knnEeeeEennk....',
        '..knEeEeeEeEnk....',
        '..kNEEvvvEENk.....',
        '...kNEvvvENk......',
        '....kEvvvEk.......',
        '...kEEkvkEEk......',
        '..kEENkkNEEk......',
        '..kENk..kNEk......',
        '...kNk..kNk.......',
        '...kNk..kNk.......',
        '..kNNk..kNNk......',
        '..kkkk..kkkk......',
        '...NN....NN.......',
        '..kNNk..kNNk......',
      ],
    ]
  ),

  'gao-elder': makeNpc(
    { q: '#d8d0c0', Q: '#9f978d', z: '#724a2b' },
    [
      [
        '......yyyyyy......',
        '.....yYYYYYYy.....',
        '.....kssssssk.....',
        '.....kskksSk......',
        '.....kQQQQQk......',
        '....kQqqqqQk......',
        '...kQqyyyyqQk.....',
        '..kYyyyyyyyyYk....',
        '..kYyYyyyyYyYk....',
        '..kYyyyyyyyyYk..z.',
        '...kYyyyyyyYk..zk.',
        '....kYYyyYYk..zk..',
        '....kYkkkkYk.zk...',
        '...kYYk..kYYkk....',
        '..kYYk....kYYk....',
        '..kYk......kYk....',
        '...kk......kk.....',
        '...Qk......Qk.....',
        '..kQk......kQk....',
        '..kk........kk....',
        '..NN........NN....',
        '.kNNk......kNNk...',
      ],
      [
        '......yyyyyy......',
        '.....yYYYYYYy.....',
        '.....kssssssk.....',
        '.....kskksSk......',
        '.....kQQQQQk......',
        '....kQqqqqQk......',
        '...kQqyyyyqQk.....',
        '..kYyyyyyyyyYk....',
        '..kYyYyyyyYyYk....',
        '..kYyyyyyyyyYk..z.',
        '...kYyyyyyyYk..zk.',
        '....kYYyyYYk..zk..',
        '....kYkkkkYk.zk...',
        '...kYYk..kYYkk....',
        '..kYYk....kYYk....',
        '..kYk......kYk....',
        '...kk......kk.....',
        '...Qk......Qk.....',
        '..kQk......kQk....',
        '..kk........kk....',
        '.NN..........NN...',
        'kNNk........kNNk..',
      ],
    ],
    [
      [
        '......yyyyyy......',
        '.....yYYYYYYy.....',
        '.....kssssssk.....',
        '.....kskkSSk......',
        '.....kQQQQQk......',
        '....kQqqqqQk......',
        '...kQqyyyyqQk.....',
        '..kYyyyyyyyyYk....',
        '..kYyYyyyyYyYk....',
        '..kYyyyyyyyyYk..z.',
        '...kYyyyyyyYk..zk.',
        '....kYYyyYYk..zk..',
        '....kYkkkkYk.zk...',
        '...kYYk..kYYkk....',
        '..kYYk....kYYk....',
        '..kYk......kYk....',
        '...kk......kk.....',
        '...Qk......Qk.....',
        '..kQk......kQk....',
        '..kk........kk....',
        '..NN........NN....',
        '.kNNk......kNNk...',
      ],
    ]
  ),

  'river-boatman': makeNpc(
    { a: '#d6b36a', A: '#8a6a35', u: '#83c8da', U: '#27677a', l: '#6b462c' },
    [
      [
        '.....aaaaaaaa.....',
        '....aAAAAAAAAa....',
        '...kkkkkkkkkkkk...',
        '.....kssssssk.....',
        '.....kskkssk......',
        '......sSSss.......',
        '....kUUUUUUk......',
        '...kUuUUUuUUk.....',
        '..kUUuUUUuUUUk....',
        '..kUUUUUUUUUUk....',
        '...kUUllllUUk.....',
        '....kUllllUk......',
        '....kUUUUUUk......',
        '...kUUk..kUUk.....',
        '..kUUk....kUUk....',
        '..kUk......kUk....',
        '...kk......kk.....',
        '...Nk......Nk.....',
        '..kNk......kNk....',
        '..kk........kk....',
        '..BB........BB....',
        '.kBBk......kBBk...',
      ],
      [
        '....aaaaaaaaaa....',
        '...aAAAAAAAAAAa...',
        '..kkkkkkkkkkkkkk..',
        '.....kssssssk.....',
        '.....kskkssk......',
        '......sSSss.......',
        '....kUUUUUUk......',
        '...kUuUUUuUUk.....',
        '..kUUuUUUuUUUk....',
        '..kUUUUUUUUUUk....',
        '...kUUllllUUk.....',
        '....kUllllUk......',
        '....kUUUUUUk......',
        '...kUUk..kUUk.....',
        '..kUUk....kUUk....',
        '..kUk......kUk....',
        '...kk......kk.....',
        '...Nk......Nk.....',
        '..kNk......kNk....',
        '..kk........kk....',
        '.BB..........BB...',
        'kBBk........kBBk..',
      ],
    ],
    [
      [
        '.....aaaaaaaa.....',
        '....aAAAAAAAAa....',
        '...kkkkkkkkkkkk...',
        '.....kssssssk.....',
        '.....kskkSSk......',
        '......sSSss.......',
        '....kUUUUUUk......',
        '...kUuUUUuUUk.....',
        '..kUUuUUUuUUUk....',
        '..kUUUUUUUUUUk....',
        '...kUUllllUUk.....',
        '....kUllllUk......',
        '....kUUUUUUk......',
        '...kUUk..kUUk.....',
        '..kUUk....kUUk....',
        '..kUk......kUk....',
        '...kk......kk.....',
        '...Nk......Nk.....',
        '..kNk......kNk....',
        '..kk........kk....',
        '..BB........BB....',
        '.kBBk......kBBk...',
      ],
    ]
  ),

  'iron-fan-maid': makeNpc(
    { f: '#f6d7a9', F: '#e7eef4', d: '#6f4268' },
    [
      [
        '......dd..dd......',
        '.....dRRRRRRd.....',
        '.....kssssssk.....',
        '.....kskkssk......',
        '......sSSss.......',
        '....krrrrrrk......',
        '...krrrRrrRRk.....',
        '..krrrrrrrrrrk....',
        '..krrfFFFFfrrk....',
        '..krrfFffFfrrk....',
        '...krrFFFFrrk.....',
        '....krrrrrrk......',
        '....krrRRrrk......',
        '...krrk..krrk.....',
        '..krrk....krrk....',
        '..krk......krk....',
        '...kk......kk.....',
        '...Rk......Rk.....',
        '..kRk......kRk....',
        '..kk........kk....',
        '..MM........MM....',
        '.kMMk......kMMk...',
      ],
      [
        '.....dd....dd.....',
        '....dRRRRRRRRd....',
        '.....kssssssk.....',
        '.....kskkssk......',
        '......sSSss.......',
        '....krrrrrrk......',
        '...krrrRrrRRk.....',
        '..krrrrrrrrrrk....',
        '..krrfFFFFfrrk....',
        '..krrfFffFfrrk....',
        '...krrFFFFrrk.....',
        '....krrrrrrk......',
        '....krrRRrrk......',
        '...krrk..krrk.....',
        '..krrk....krrk....',
        '..krk......krk....',
        '...kk......kk.....',
        '...Rk......Rk.....',
        '..kRk......kRk....',
        '..kk........kk....',
        '.MM..........MM...',
        'kMMk........kMMk..',
      ],
    ],
    [
      [
        '......dd..dd......',
        '.....dRRRRRRd.....',
        '.....kssssssk.....',
        '.....kskkSSk......',
        '......sSSss.......',
        '....krrrrrrk......',
        '...krrrRrrRRk.....',
        '..krrrrrrrrrrk....',
        '..krrfFFFFfrrk....',
        '..krrfFffFfrrk....',
        '...krrFFFFrrk.....',
        '....krrrrrrk......',
        '....krrRRrrk......',
        '...krrk..krrk.....',
        '..krrk....krrk....',
        '..krk......krk....',
        '...kk......kk.....',
        '...Rk......Rk.....',
        '..kRk......kRk....',
        '..kk........kk....',
        '..MM........MM....',
        '.kMMk......kMMk...',
      ],
    ]
  ),

  'lingshan-monk': makeNpc(
    { h: '#ffe9a8', j: '#f0b84f', J: '#9c6f2b', c: '#9b6b3a' },
    [
      [
        '.......hhh........',
        '......h...h.......',
        '.......kJk........',
        '.....ksssssk......',
        '.....kskkssk......',
        '......sSSss.......',
        '....kjjjjjjk......',
        '...kjjJJJjjjk.....',
        '..kjjjjjjjjjjk....',
        '..kjjcjcjcjjjk....',
        '...kjjjJJjjjk.....',
        '....kjjjjjjk......',
        '....kjjJJjjk......',
        '...kjjk..kjjk.....',
        '..kjjk....kjjk....',
        '..kjk......kjk....',
        '...kk......kk.....',
        '...Jk......Jk.....',
        '..kJk......kJk....',
        '..kk........kk....',
        '..NN........NN....',
        '.kNNk......kNNk...',
      ],
      [
        '.......hhh........',
        '......h...h.......',
        '.......kJk........',
        '.....ksssssk......',
        '.....kskkssk......',
        '......sSSss.......',
        '....kjjjjjjk......',
        '...kjjJJJjjjk.....',
        '..kjjjjjjjjjjk....',
        '..kjjcjcjcjjjk....',
        '...kjjjJJjjjk.....',
        '....kjjjjjjk......',
        '....kjjJJjjk......',
        '...kjjk..kjjk.....',
        '..kjjk....kjjk....',
        '..kjk......kjk....',
        '...kk......kk.....',
        '...Jk......Jk.....',
        '..kJk......kJk....',
        '..kk........kk....',
        '.NN..........NN...',
        'kNNk........kNNk..',
      ],
    ],
    [
      [
        '.......hhh........',
        '......h...h.......',
        '.......kJk........',
        '.....ksssssk......',
        '.....kskkSSk......',
        '......sSSss.......',
        '....kjjjjjjk......',
        '...kjjJJJjjjk.....',
        '..kjjjjjjjjjjk....',
        '..kjjcjcjcjjjk....',
        '...kjjjJJjjjk.....',
        '....kjjjjjjk......',
        '....kjjJJjjk......',
        '...kjjk..kjjk.....',
        '..kjjk....kjjk....',
        '..kjk......kjk....',
        '...kk......kk.....',
        '...Jk......Jk.....',
        '..kJk......kJk....',
        '..kk........kk....',
        '..NN........NN....',
        '.kNNk......kNNk...',
      ],
    ]
  ),
};

export function npcFrame(npcKey, talking, clock) {
  const character = NPC_SPRITES[npcKey] || NPC_SPRITES.guanyin;
  const frames = talking ? character.run : character.idle;
  const fps = talking ? 6 : 2.2;
  const idx = Math.floor(Math.max(0, clock) * fps) % frames.length;
  return { data: frames[idx], palette: character.palette, character };
}
