// AUTO-GENERATED from arts/沙僧.png by tmp_art/build_party.py - do not edit by hand.
// 月色（moonlit）像素沙僧：front-view run + idle 帧。'.' = 透明。
// feetRow = 角色脚底所在行（用于让脚踩在地面 y 上）。

export const SHASENG = {
  w: 24,
  h: 26,
  feetRow: 25,
  palette: {
    '.': null,
    'a': '#575947',
    'b': '#a39b7f',
    'c': '#484848',
    'd': '#cbbc94',
    'e': '#222a37',
    'f': '#6d6858',
    'g': '#c4904a',
    'h': '#323439',
    'i': '#365f62',
    'j': '#694e30',
    'k': '#a5885a',
    'l': '#957245',
    'm': '#846139',
    'n': '#705b3e',
    'o': '#302f38',
    'p': '#36424a',
    'q': '#001b2d',
    'r': '#493d38',
    's': '#857244',
    't': '#604a36',
    'u': '#443732',
    'v': '#362b29',
    'w': '#dea24b',
    'x': '#f1c776',
    'y': '#523b2e',
    'z': '#7f4a27',
    'A': '#5d3f27',
    'B': '#181926',
    'C': '#c06e2d',
    'D': '#3e2a25',
    'E': '#544636',
    'F': '#2e2222',
    'G': '#1e2530',
    'H': '#2f2a2d',
    'I': '#1f1f27',
    'J': '#244052',
    'K': '#f2da9a',
    'L': '#fdf7c2',
    'M': '#3a3c32',
    'N': '#d6deec',
    'O': '#282030',
    'P': '#96a8c8',
    'Q': '#3c3242',
  },
  run: [
    [
      '........................',
      '........................',
      '...................ab...',
      '....................cd..',
      '....................efd.',
      '.........gggg.......hib.',
      '........jklmnmo...fppfb.',
      '.......qerjlmmh...sftlt.',
      '.......uvgkwxgmy..zzjA..',
      '......BCjggwxklm...nmy..',
      '......eADEwxxxnF...ty...',
      '......eeFBvErrFF...o....',
      '....FEcDyBuuGDyv..h.....',
      '....otCyFytnrDvr..e.....',
      '....iajeayFyFyhinmm.....',
      '...eifpGaEeDHuefzgw.....',
      '...hlljoHhrAyHBaFyt.....',
      '...rAlmHvvuFDDIhHeH.....',
      '....ugsJvjopozyIho......',
      '..K..BGotArJpAyIHh......',
      '.KLK.Ivtthfiiurvo..K....',
      '.KKKK.orpvfffruBh.KLK...',
      '........MM..MM..........',
      '........wM..wM..........',
      '......N.OO.NOOP.........',
      '.......QOO..OOQ.........',
    ],
    [
      '....................ab..',
      '.....................cd.',
      '.....................efd',
      '..........gggg.......hib',
      '.........jklmnmo...fppfb',
      '........qerjlmmh...sftlt',
      '........uvgkwxgmy..zzjA.',
      '.......BCjggwxklm...nmy.',
      '.......eADEwxxxnF...ty..',
      '.......eeFBvErrFF...o...',
      '.....FEcDyBuuGDyv..h....',
      '.....otCyFytnrDvr..e....',
      '.....iajeayFyFyhinmm....',
      '....eifpGaEeDHuefzgw....',
      '....hlljoHhrAyHBaFyt....',
      '....rAlmHvvuFDDIhHeH....',
      '.....ugsJvjopozyIho.....',
      '...K..BGotArJpAyIHh.....',
      '..KLK.Ivtthfiiurvo..K...',
      '..KKKK.orpvfffruBh.KLK..',
      '.........wM.............',
      '.........OO.MM..........',
      '........QOO.MM..........',
      '............wM..........',
      '............OOP.........',
      '............OOQ.........',
    ],
    [
      '....................ab..',
      '.....................cd.',
      '.....................efd',
      '..........gggg.......hib',
      '.........jklmnmo...fppfb',
      '........qerjlmmh...sftlt',
      '........uvgkwxgmy..zzjA.',
      '.......BCjggwxklm...nmy.',
      '.......eADEwxxxnF...ty..',
      '.......eeFBvErrFF...o...',
      '.....FEcDyBuuGDyv..h....',
      '.....otCyFytnrDvr..e....',
      '.....iajeayFyFyhinmm....',
      '....eifpGaEeDHuefzgw....',
      '....hlljoHhrAyHBaFyt....',
      '....rAlmHvvuFDDIhHeH....',
      '.....ugsJvjopozyIho.....',
      '...K..BGotArJpAyIHh.....',
      '..KLK.Ivtthfiiurvo..K...',
      '..KKKK.orpvfffruBh.KLK..',
      '.........wM.............',
      '.........OO.MM..........',
      '........QOO.MM..........',
      '............wM..........',
      '...........NOOP.........',
      '............OOQ.........',
    ],
    [
      '........................',
      '........................',
      '...................ab...',
      '....................cd..',
      '....................efd.',
      '.........gggg.......hib.',
      '........jklmnmo...fppfb.',
      '.......qerjlmmh...sftlt.',
      '.......uvgkwxgmy..zzjA..',
      '......BCjggwxklm...nmy..',
      '......eADEwxxxnF...ty...',
      '......eeFBvErrFF...o....',
      '....FEcDyBuuGDyv..h.....',
      '....otCyFytnrDvr..e.....',
      '....iajeayFyFyhinmm.....',
      '...eifpGaEeDHuefzgw.....',
      '...hlljoHhrAyHBaFyt.....',
      '...rAlmHvvuFDDIhHeH.....',
      '....ugsJvjopozyIho......',
      '..K..BGotArJpAyIHh......',
      '.KLK.Ivtthfiiurvo..K....',
      '.KKKK.orpvfffruBh.KLK...',
      '........MM..MM..........',
      '........wM..wM..........',
      '........OO..OOP.........',
      '.......QOO..OOQ.........',
    ],
    [
      '..................ab....',
      '...................cd...',
      '...................efd..',
      '........gggg.......hib..',
      '.......jklmnmo...fppfb..',
      '......qerjlmmh...sftlt..',
      '......uvgkwxgmy..zzjA...',
      '.....BCjggwxklm...nmy...',
      '.....eADEwxxxnF...ty....',
      '.....eeFBvErrFF...o.....',
      '...FEcDyBuuGDyv..h......',
      '...otCyFytnrDvr..e......',
      '...iajeayFyFyhinmm......',
      '..eifpGaEeDHuefzgw......',
      '..hlljoHhrAyHBaFyt......',
      '..rAlmHvvuFDDIhHeH......',
      '...ugsJvjopozyIho.......',
      '.K..BGotArJpAyIHh.......',
      'KLK.Ivtthfiiurvo..K.....',
      'KKKK.orpvfffruBh.KLK....',
      '...........wM...........',
      '........MM.OO...........',
      '........MM.OOQ..........',
      '........wM..............',
      '......N.OO..............',
      '.......QOO..............',
    ],
    [
      '..................ab....',
      '...................cd...',
      '...................efd..',
      '........gggg.......hib..',
      '.......jklmnmo...fppfb..',
      '......qerjlmmh...sftlt..',
      '......uvgkwxgmy..zzjA...',
      '.....BCjggwxklm...nmy...',
      '.....eADEwxxxnF...ty....',
      '.....eeFBvErrFF...o.....',
      '...FEcDyBuuGDyv..h......',
      '...otCyFytnrDvr..e......',
      '...iajeayFyFyhinmm......',
      '..eifpGaEeDHuefzgw......',
      '..hlljoHhrAyHBaFyt......',
      '..rAlmHvvuFDDIhHeH......',
      '...ugsJvjopozyIho.......',
      '.K..BGotArJpAyIHh.......',
      'KLK.Ivtthfiiurvo..K.....',
      'KKKK.orpvfffruBh.KLK....',
      '...........wM...........',
      '........MM.OO...........',
      '........MM.OOQ..........',
      '........wM..............',
      '........OO..............',
      '.......QOO..............',
    ],
  ],
  idle: [
    [
      '........................',
      '........................',
      '...................ab...',
      '....................cd..',
      '....................efd.',
      '.........gggg.......hib.',
      '........jklmnmo...fppfb.',
      '.......qerjlmmh...sftlt.',
      '.......uvgkwxgmy..zzjA..',
      '......BCjggwxklm...nmy..',
      '......eADEwxxxnF...ty...',
      '......eeFBvErrFF...o....',
      '....FEcDyBuuGDyv..h.....',
      '....otCyFytnrDvr..e.....',
      '....iajeayFyFyhinmm.....',
      '...eifpGaEeDHuefzgw.....',
      '...hlljoHhrAyHBaFyt.....',
      '...rAlmHvvuFDDIhHeH.....',
      '....ugsJvjopozyIho......',
      '..K..BGotArJpAyIHh......',
      '.KLK.Ivtthfiiurvo..K....',
      '.KKKK.orpvfffruBh.KLK...',
      '........MM..MM..........',
      '........wM..wM..........',
      '........OO..OO..........',
      '.......QOO..OOQ.........',
    ],
    [
      '........................',
      '...................ab...',
      '....................cd..',
      '....................efd.',
      '.........gggg.......hib.',
      '........jklmnmo...fppfb.',
      '.......qerjlmmh...sftlt.',
      '.......uvgkwxgmy..zzjA..',
      '......BCjggwxklm...nmy..',
      '......eADEwxxxnF...ty...',
      '......eeFBvErrFF...o....',
      '....FEcDyBuuGDyv..h.....',
      '....otCyFytnrDvr..e.....',
      '....iajeayFyFyhinmm.....',
      '...eifpGaEeDHuefzgw.....',
      '...hlljoHhrAyHBaFyt.....',
      '...rAlmHvvuFDDIhHeH.....',
      '....ugsJvjopozyIho......',
      '..K..BGotArJpAyIHh......',
      '.KLK.Ivtthfiiurvo..K....',
      '.KKKK.orpvfffruBh.KLK...',
      '........MM..MM..........',
      '........MM..MM..........',
      '........wM..wM..........',
      '........OO..OO..........',
      '.......QOO..OOQ.........',
    ],
  ],
};
