// AUTO-GENERATED from arts/孙悟空.png by tmp_art/build.py — do not edit by hand.
// 月色（moonlit）像素孙悟空：front-view run + idle 帧。'.' = 透明。
// feetRow = 角色脚底所在行（用于让脚踩在地面 y 上）。

export const WUKONG = {
  w: 24,
  h: 26,
  feetRow: 25,
  palette: {
    '.': null,
    'a': '#70452a',
    'b': '#433329',
    'c': '#33221d',
    'd': '#7a5538',
    'e': '#9c6138',
    'f': '#81552d',
    'g': '#3e2a20',
    'h': '#704021',
    'i': '#d79a3b',
    'j': '#9c713e',
    'k': '#5f3928',
    'l': '#714a2f',
    'm': '#895f39',
    'n': '#976121',
    'o': '#8c5530',
    'p': '#9f824c',
    'q': '#c97c3d',
    'r': '#191919',
    's': '#522f21',
    't': '#685137',
    'u': '#874624',
    'v': '#ceb890',
    'w': '#bc965a',
    'x': '#523726',
    'y': '#efb057',
    'z': '#f0dcaf',
    'A': '#682f20',
    'B': '#521a17',
    'C': '#5f241e',
    'D': '#351515',
    'E': '#5b4227',
    'F': '#eed79a',
    'G': '#fcf4cd',
    'H': '#ebce8f',
    'I': '#704628',
    'J': '#d6deec',
    'K': '#282030',
    'L': '#96a8c8',
    'M': '#3c3242',
  },
  run: [
    [
      '........................',
      '........................',
      '..........ab............',
      '.........cdefga.....hij.',
      '.......gkalmemffc...fin.',
      '.......glmemdddof...ji..',
      '......ballddpmjdd...qq..',
      '......rsfejjiqijlc..qn..',
      '......taunjpfhfnhc.fih..',
      '.....mvwxlvvwmwvkp.hj...',
      '.....myekeztvzpplq.hA...',
      '......jexfvwvzvpho.us...',
      '......rgsmzzzzmr..u.....',
      '.......qjBAddkc..CA.....',
      '..xdk.niqshBBBnsdpd.....',
      '..bba.CoAhiAkBsAkyp.....',
      '....kgneDgtaqxcCDmx.....',
      '....xsuEbDcnqhbplC......',
      '..FF.kobknjtCmjvmC......',
      '.FzG.sjehivauhpje..z....',
      '.FGGF.twvvbnquCaj.zGz...',
      '..HHH.cdmCDnhAChnvzzz...',
      '........II..II..........',
      '........iI..iI..........',
      '......J.KK.JKKL.........',
      '.......MKK..KKM.........',
    ],
    [
      '...........ab...........',
      '..........cdefga.....hij',
      '........gkalmemffc...fin',
      '........glmemdddof...ji.',
      '.......ballddpmjdd...qq.',
      '.......rsfejjiqijlc..qn.',
      '.......taunjpfhfnhc.fih.',
      '......mvwxlvvwmwvkp.hj..',
      '......myekeztvzpplq.hA..',
      '.......jexfvwvzvpho.us..',
      '.......rgsmzzzzmr..u....',
      '........qjBAddkc..CA....',
      '...xdk.niqshBBBnsdpd....',
      '...bba.CoAhiAkBsAkyp....',
      '.....kgneDgtaqxcCDmx....',
      '.....xsuEbDcnqhbplC.....',
      '...FF.kobknjtCmjvmC.....',
      '..FzG.sjehivauhpje..z...',
      '..FGGF.twvvbnquCaj.zGz..',
      '...HHH.cdmCDnhAChnvzzz..',
      '.........iI.............',
      '.........KK.II..........',
      '........MKK.II..........',
      '............iI..........',
      '............KKL.........',
      '............KKM.........',
    ],
    [
      '...........ab...........',
      '..........cdefga.....hij',
      '........gkalmemffc...fin',
      '........glmemdddof...ji.',
      '.......ballddpmjdd...qq.',
      '.......rsfejjiqijlc..qn.',
      '.......taunjpfhfnhc.fih.',
      '......mvwxlvvwmwvkp.hj..',
      '......myekeztvzpplq.hA..',
      '.......jexfvwvzvpho.us..',
      '.......rgsmzzzzmr..u....',
      '........qjBAddkc..CA....',
      '...xdk.niqshBBBnsdpd....',
      '...bba.CoAhiAkBsAkyp....',
      '.....kgneDgtaqxcCDmx....',
      '.....xsuEbDcnqhbplC.....',
      '...FF.kobknjtCmjvmC.....',
      '..FzG.sjehivauhpje..z...',
      '..FGGF.twvvbnquCaj.zGz..',
      '...HHH.cdmCDnhAChnvzzz..',
      '.........iI.............',
      '.........KK.II..........',
      '........MKK.II..........',
      '............iI..........',
      '...........JKKL.........',
      '............KKM.........',
    ],
    [
      '........................',
      '........................',
      '..........ab............',
      '.........cdefga.....hij.',
      '.......gkalmemffc...fin.',
      '.......glmemdddof...ji..',
      '......ballddpmjdd...qq..',
      '......rsfejjiqijlc..qn..',
      '......taunjpfhfnhc.fih..',
      '.....mvwxlvvwmwvkp.hj...',
      '.....myekeztvzpplq.hA...',
      '......jexfvwvzvpho.us...',
      '......rgsmzzzzmr..u.....',
      '.......qjBAddkc..CA.....',
      '..xdk.niqshBBBnsdpd.....',
      '..bba.CoAhiAkBsAkyp.....',
      '....kgneDgtaqxcCDmx.....',
      '....xsuEbDcnqhbplC......',
      '..FF.kobknjtCmjvmC......',
      '.FzG.sjehivauhpje..z....',
      '.FGGF.twvvbnquCaj.zGz...',
      '..HHH.cdmCDnhAChnvzzz...',
      '........II..II..........',
      '........iI..iI..........',
      '........KK..KKL.........',
      '.......MKK..KKM.........',
    ],
    [
      '.........ab.............',
      '........cdefga.....hij..',
      '......gkalmemffc...fin..',
      '......glmemdddof...ji...',
      '.....ballddpmjdd...qq...',
      '.....rsfejjiqijlc..qn...',
      '.....taunjpfhfnhc.fih...',
      '....mvwxlvvwmwvkp.hj....',
      '....myekeztvzpplq.hA....',
      '.....jexfvwvzvpho.us....',
      '.....rgsmzzzzmr..u......',
      '......qjBAddkc..CA......',
      '.xdk.niqshBBBnsdpd......',
      '.bba.CoAhiAkBsAkyp......',
      '...kgneDgtaqxcCDmx......',
      '...xsuEbDcnqhbplC.......',
      '.FF.kobknjtCmjvmC.......',
      'FzG.sjehivauhpje..z.....',
      'FGGF.twvvbnquCaj.zGz....',
      '.HHH.cdmCDnhAChnvzzz....',
      '...........iI...........',
      '........II.KK...........',
      '........II.KKM..........',
      '........iI..............',
      '......J.KK..............',
      '.......MKK..............',
    ],
    [
      '.........ab.............',
      '........cdefga.....hij..',
      '......gkalmemffc...fin..',
      '......glmemdddof...ji...',
      '.....ballddpmjdd...qq...',
      '.....rsfejjiqijlc..qn...',
      '.....taunjpfhfnhc.fih...',
      '....mvwxlvvwmwvkp.hj....',
      '....myekeztvzpplq.hA....',
      '.....jexfvwvzvpho.us....',
      '.....rgsmzzzzmr..u......',
      '......qjBAddkc..CA......',
      '.xdk.niqshBBBnsdpd......',
      '.bba.CoAhiAkBsAkyp......',
      '...kgneDgtaqxcCDmx......',
      '...xsuEbDcnqhbplC.......',
      '.FF.kobknjtCmjvmC.......',
      'FzG.sjehivauhpje..z.....',
      'FGGF.twvvbnquCaj.zGz....',
      '.HHH.cdmCDnhAChnvzzz....',
      '...........iI...........',
      '........II.KK...........',
      '........II.KKM..........',
      '........iI..............',
      '........KK..............',
      '.......MKK..............',
    ],
  ],
  idle: [
    [
      '........................',
      '........................',
      '..........ab............',
      '.........cdefga.....hij.',
      '.......gkalmemffc...fin.',
      '.......glmemdddof...ji..',
      '......ballddpmjdd...qq..',
      '......rsfejjiqijlc..qn..',
      '......taunjpfhfnhc.fih..',
      '.....mvwxlvvwmwvkp.hj...',
      '.....myekeztvzpplq.hA...',
      '......jexfvwvzvpho.us...',
      '......rgsmzzzzmr..u.....',
      '.......qjBAddkc..CA.....',
      '..xdk.niqshBBBnsdpd.....',
      '..bba.CoAhiAkBsAkyp.....',
      '....kgneDgtaqxcCDmx.....',
      '....xsuEbDcnqhbplC......',
      '..FF.kobknjtCmjvmC......',
      '.FzG.sjehivauhpje..z....',
      '.FGGF.twvvbnquCaj.zGz...',
      '..HHH.cdmCDnhAChnvzzz...',
      '........II..II..........',
      '........iI..iI..........',
      '........KK..KK..........',
      '.......MKK..KKM.........',
    ],
    [
      '........................',
      '..........ab............',
      '.........cdefga.....hij.',
      '.......gkalmemffc...fin.',
      '.......glmemdddof...ji..',
      '......ballddpmjdd...qq..',
      '......rsfejjiqijlc..qn..',
      '......taunjpfhfnhc.fih..',
      '.....mvwxlvvwmwvkp.hj...',
      '.....myekeztvzpplq.hA...',
      '......jexfvwvzvpho.us...',
      '......rgsmzzzzmr..u.....',
      '.......qjBAddkc..CA.....',
      '..xdk.niqshBBBnsdpd.....',
      '..bba.CoAhiAkBsAkyp.....',
      '....kgneDgtaqxcCDmx.....',
      '....xsuEbDcnqhbplC......',
      '..FF.kobknjtCmjvmC......',
      '.FzG.sjehivauhpje..z....',
      '.FGGF.twvvbnquCaj.zGz...',
      '..HHH.cdmCDnhAChnvzzz...',
      '........II..II..........',
      '........II..II..........',
      '........iI..iI..........',
      '........KK..KK..........',
      '.......MKK..KKM.........',
    ],
  ],
};
