// AUTO-GENERATED from arts/孙悟空.png by tmp_art/build_party.py - do not edit by hand.
// 月色（moonlit）像素孙悟空：front-view run + idle 帧。'.' = 透明。
// feetRow = 角色脚底所在行（用于让脚踩在地面 y 上）。

export const WUKONG = {
  w: 24,
  h: 26,
  feetRow: 25,
  palette: {
    '.': null,
    'a': '#70452a',
    'b': '#432f26',
    'c': '#33221d',
    'd': '#7a5538',
    'e': '#9c6138',
    'f': '#81552d',
    'g': '#3e2a20',
    'h': '#704021',
    'i': '#d79a3b',
    'j': '#9f7c2d',
    'k': '#5f3928',
    'l': '#714a2f',
    'm': '#895f39',
    'n': '#976121',
    'o': '#8c5530',
    'p': '#9c713e',
    'q': '#191919',
    'r': '#522f21',
    's': '#c97c3d',
    't': '#685137',
    'u': '#874624',
    'v': '#ceb890',
    'w': '#9f8768',
    'x': '#523726',
    'y': '#bc965a',
    'z': '#efb057',
    'A': '#f0dcaf',
    'B': '#682f20',
    'C': '#521a17',
    'D': '#5f241e',
    'E': '#351515',
    'F': '#5b4227',
    'G': '#44372c',
    'H': '#eed79a',
    'I': '#fcf4cd',
    'J': '#ebce8f',
    'K': '#704629',
    'L': '#d6deec',
    'M': '#282030',
    'N': '#96a8c8',
    'O': '#3c3242',
  },
  run: [
    [
      '........................',
      '........................',
      '..........ab............',
      '.........cdefga.....hij.',
      '.......bkalmemffc...fin.',
      '.......blmemdddof...ji..',
      '......ballddpmjdd...jj..',
      '......qrfepjisijlc..sn..',
      '......taunjpfhfnhc.fih..',
      '.....mvwxlvvwmyvkp.hj...',
      '.....mzekeAtvAwwls.hB...',
      '......pexfvwvAvwho.ur...',
      '......qgrmAAAAmq..u.....',
      '.......spCBddkc..DB.....',
      '..xdk.nijrhCCCnrdpd.....',
      '..bba.DoBhiBkCrBkzp.....',
      '....kgneEgtasxcDEmx.....',
      '....xruFGEcnshGwlD......',
      '..HH.koGknptDmpvmD......',
      '.HAI.rpehivauhwpe..A....',
      '.HIIH.tyvvGnsuDaj.AIA...',
      '..JJJ.cdmDEnhBDhnvAAA...',
      '........KK..KK..........',
      '........iK..iK..........',
      '......L.MM.LMMN.........',
      '.......OMM..MMO.........',
    ],
    [
      '...........ab...........',
      '..........cdefga.....hij',
      '........bkalmemffc...fin',
      '........blmemdddof...ji.',
      '.......ballddpmjdd...jj.',
      '.......qrfepjisijlc..sn.',
      '.......taunjpfhfnhc.fih.',
      '......mvwxlvvwmyvkp.hj..',
      '......mzekeAtvAwwls.hB..',
      '.......pexfvwvAvwho.ur..',
      '.......qgrmAAAAmq..u....',
      '........spCBddkc..DB....',
      '...xdk.nijrhCCCnrdpd....',
      '...bba.DoBhiBkCrBkzp....',
      '.....kgneEgtasxcDEmx....',
      '.....xruFGEcnshGwlD.....',
      '...HH.koGknptDmpvmD.....',
      '..HAI.rpehivauhwpe..A...',
      '..HIIH.tyvvGnsuDaj.AIA..',
      '...JJJ.cdmDEnhBDhnvAAA..',
      '.........iK.............',
      '.........MM.KK..........',
      '........OMM.KK..........',
      '............iK..........',
      '............MMN.........',
      '............MMO.........',
    ],
    [
      '...........ab...........',
      '..........cdefga.....hij',
      '........bkalmemffc...fin',
      '........blmemdddof...ji.',
      '.......ballddpmjdd...jj.',
      '.......qrfepjisijlc..sn.',
      '.......taunjpfhfnhc.fih.',
      '......mvwxlvvwmyvkp.hj..',
      '......mzekeAtvAwwls.hB..',
      '.......pexfvwvAvwho.ur..',
      '.......qgrmAAAAmq..u....',
      '........spCBddkc..DB....',
      '...xdk.nijrhCCCnrdpd....',
      '...bba.DoBhiBkCrBkzp....',
      '.....kgneEgtasxcDEmx....',
      '.....xruFGEcnshGwlD.....',
      '...HH.koGknptDmpvmD.....',
      '..HAI.rpehivauhwpe..A...',
      '..HIIH.tyvvGnsuDaj.AIA..',
      '...JJJ.cdmDEnhBDhnvAAA..',
      '.........iK.............',
      '.........MM.KK..........',
      '........OMM.KK..........',
      '............iK..........',
      '...........LMMN.........',
      '............MMO.........',
    ],
    [
      '........................',
      '........................',
      '..........ab............',
      '.........cdefga.....hij.',
      '.......bkalmemffc...fin.',
      '.......blmemdddof...ji..',
      '......ballddpmjdd...jj..',
      '......qrfepjisijlc..sn..',
      '......taunjpfhfnhc.fih..',
      '.....mvwxlvvwmyvkp.hj...',
      '.....mzekeAtvAwwls.hB...',
      '......pexfvwvAvwho.ur...',
      '......qgrmAAAAmq..u.....',
      '.......spCBddkc..DB.....',
      '..xdk.nijrhCCCnrdpd.....',
      '..bba.DoBhiBkCrBkzp.....',
      '....kgneEgtasxcDEmx.....',
      '....xruFGEcnshGwlD......',
      '..HH.koGknptDmpvmD......',
      '.HAI.rpehivauhwpe..A....',
      '.HIIH.tyvvGnsuDaj.AIA...',
      '..JJJ.cdmDEnhBDhnvAAA...',
      '........KK..KK..........',
      '........iK..iK..........',
      '........MM..MMN.........',
      '.......OMM..MMO.........',
    ],
    [
      '.........ab.............',
      '........cdefga.....hij..',
      '......bkalmemffc...fin..',
      '......blmemdddof...ji...',
      '.....ballddpmjdd...jj...',
      '.....qrfepjisijlc..sn...',
      '.....taunjpfhfnhc.fih...',
      '....mvwxlvvwmyvkp.hj....',
      '....mzekeAtvAwwls.hB....',
      '.....pexfvwvAvwho.ur....',
      '.....qgrmAAAAmq..u......',
      '......spCBddkc..DB......',
      '.xdk.nijrhCCCnrdpd......',
      '.bba.DoBhiBkCrBkzp......',
      '...kgneEgtasxcDEmx......',
      '...xruFGEcnshGwlD.......',
      '.HH.koGknptDmpvmD.......',
      'HAI.rpehivauhwpe..A.....',
      'HIIH.tyvvGnsuDaj.AIA....',
      '.JJJ.cdmDEnhBDhnvAAA....',
      '...........iK...........',
      '........KK.MM...........',
      '........KK.MMO..........',
      '........iK..............',
      '......L.MM..............',
      '.......OMM..............',
    ],
    [
      '.........ab.............',
      '........cdefga.....hij..',
      '......bkalmemffc...fin..',
      '......blmemdddof...ji...',
      '.....ballddpmjdd...jj...',
      '.....qrfepjisijlc..sn...',
      '.....taunjpfhfnhc.fih...',
      '....mvwxlvvwmyvkp.hj....',
      '....mzekeAtvAwwls.hB....',
      '.....pexfvwvAvwho.ur....',
      '.....qgrmAAAAmq..u......',
      '......spCBddkc..DB......',
      '.xdk.nijrhCCCnrdpd......',
      '.bba.DoBhiBkCrBkzp......',
      '...kgneEgtasxcDEmx......',
      '...xruFGEcnshGwlD.......',
      '.HH.koGknptDmpvmD.......',
      'HAI.rpehivauhwpe..A.....',
      'HIIH.tyvvGnsuDaj.AIA....',
      '.JJJ.cdmDEnhBDhnvAAA....',
      '...........iK...........',
      '........KK.MM...........',
      '........KK.MMO..........',
      '........iK..............',
      '........MM..............',
      '.......OMM..............',
    ],
  ],
  idle: [
    [
      '........................',
      '........................',
      '..........ab............',
      '.........cdefga.....hij.',
      '.......bkalmemffc...fin.',
      '.......blmemdddof...ji..',
      '......ballddpmjdd...jj..',
      '......qrfepjisijlc..sn..',
      '......taunjpfhfnhc.fih..',
      '.....mvwxlvvwmyvkp.hj...',
      '.....mzekeAtvAwwls.hB...',
      '......pexfvwvAvwho.ur...',
      '......qgrmAAAAmq..u.....',
      '.......spCBddkc..DB.....',
      '..xdk.nijrhCCCnrdpd.....',
      '..bba.DoBhiBkCrBkzp.....',
      '....kgneEgtasxcDEmx.....',
      '....xruFGEcnshGwlD......',
      '..HH.koGknptDmpvmD......',
      '.HAI.rpehivauhwpe..A....',
      '.HIIH.tyvvGnsuDaj.AIA...',
      '..JJJ.cdmDEnhBDhnvAAA...',
      '........KK..KK..........',
      '........iK..iK..........',
      '........MM..MM..........',
      '.......OMM..MMO.........',
    ],
    [
      '........................',
      '..........ab............',
      '.........cdefga.....hij.',
      '.......bkalmemffc...fin.',
      '.......blmemdddof...ji..',
      '......ballddpmjdd...jj..',
      '......qrfepjisijlc..sn..',
      '......taunjpfhfnhc.fih..',
      '.....mvwxlvvwmyvkp.hj...',
      '.....mzekeAtvAwwls.hB...',
      '......pexfvwvAvwho.ur...',
      '......qgrmAAAAmq..u.....',
      '.......spCBddkc..DB.....',
      '..xdk.nijrhCCCnrdpd.....',
      '..bba.DoBhiBkCrBkzp.....',
      '....kgneEgtasxcDEmx.....',
      '....xruFGEcnshGwlD......',
      '..HH.koGknptDmpvmD......',
      '.HAI.rpehivauhwpe..A....',
      '.HIIH.tyvvGnsuDaj.AIA...',
      '..JJJ.cdmDEnhBDhnvAAA...',
      '........KK..KK..........',
      '........KK..KK..........',
      '........iK..iK..........',
      '........MM..MM..........',
      '.......OMM..MMO.........',
    ],
  ],
};
